a=400000;b=350000;c=13;d=21;e= a-(a*c/100);f=b-(b*d/100)
print("Harga sepatu A adalah", a)
print("Harga sepatu B adalah", b)
print("Sepatu A mendapat diskon 13%% sehingga harganya menjadi", round(e))
print("Sepatu B mendapat diskon 21%% sehingga harganya menjadi", round(f))