namaa = input("Nama \t\t\t: ")
nimm = input("NIM \t\t\t: ")
kelazz = input("Kelas Paralel \t\t: ")
tempattanggal_lahirz = input("Tempat/Tanggal Lahir \t: ")
alamatz = input("Alamat \t\t\t: ")
hobbyz = input("Hobby \t\t\t: ")
no_hpz = input("No. HP \t\t\t: ")

print(f"Nama \t\t\t: {namaa}")
print(f"NIM \t\t\t: {nimm}")
print(f"Kelas Paralel \t\t: {kelazz}")
print(f"Tempat/Tanggal Lahir \t: {tempattanggal_lahirz}")
print(f"Alamat \t\t\t: {alamatz}")
print(f"Hobby \t\t\t: {hobbyz}")
print(f"No. HP \t\t\t: {no_hpz}")
